---
fixtures:
  repositories:
    concat:  https://github.com/simp/puppetlabs-concat.git
    inifile: https://github.com/simp/puppetlabs-inifile.git
    polkit:  https://github.com/simp/pupmod-simp-polkit.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib:  https://github.com/simp/puppetlabs-stdlib.git
